---
services:
  jenkins:
    build:
      context: jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"    # Jenkins web UI
      - "50000:50000"  # Jenkins agent port
      - "8769:8769"    # Game server port (for testing) (for testing) (for testing) (for testing)
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount project source for development (optional)
      - ../:/opt/sample_gaming_sut:ro
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - JAVA_OPTS=-Xmx2g -Dhudson.footerURL=http://sample-gaming-sut
      # Timezone
      - TZ=UTC
    networks:
      - jenkins-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/login || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: Game server for testing (can be started/stopped by Jenkins)
  game-server:
    image: python:3.11-slim
    container_name: game-server-sut
    restart: "no"  # Controlled by Jenkins
    ports:
      - "8767:8767"
    volumes:
      - ../:/app
    working_dir: /app
    command: ["tail", "-f", "/dev/null"]  # Keep container running
    networks:
      - jenkins-network
    profiles:
      - testing  # Only start with --profile testing

volumes:
  jenkins_home:

networks:
  jenkins-network:
    driver: bridge